### ISSUE TITLE
and to change the size of spaces?

### ISSUE THREAD

**Issue by ArkIv** [okitavera/vscode-nunjucks-formatter#3]
a how to remove empty lines?
and to change the size of spaces?

**Comment by okitavera** [comment]
I think empty lines is not something that any formatter should remove automatically since it would affect text spaces on the html.
But you can set indentation size on the vscode setting (global, workspace, or per-file on the status bar) since this extension read from it.

**Comment by ArkIv** [comment]
Thanks. dealt with a space, and about lines, I meant, not gaps namely the whole empty lines.
I had different spaces in different tabs :(
