### ISSUE TITLE
Respect .editorconfig configuration

### ISSUE THREAD

**Issue by justrhysism** [okitavera/vscode-nunjucks-formatter#6]
The formatter should respect editorconfig settings.

**Comment by okitavera** [comment]
can you tell me more details about it ?
I also using editorconfig and it works pretty well here [.editorconfig](https://github.com/okitavera/okitavera.me/blob/master/.editorconfig)

**Comment by justrhysism** [comment]
Apologies, I think this may have actually been caused by #5

**Comment by okitavera** [comment]
Oh, I will close this if it was a duplicate

**Comment by AlphaCodeZero** [comment]
I think 'insert_final_newline' isn't respected. When I save a file, this nunjucks-formatter will delete the final empty line first, and then either 'files.insertFinalNewline' or 'insert_final_newline' in .editorconfig will take effect, leaving the file being saved twice. @okitavera
